service: nest-api-module8

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: epam_bipin
  region: ap-south-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
