service: nest-api-module8

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: epam_bipin
  region: ap-south-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    environment:
      HOST: ${env:HOST}
      PORT: ${env:PORT}
      DB_USERNAME: ${env:DB_USERNAME}
      PASSWORD: ${env:PASSWORD}
      DATABASE: ${env:DATABASE}
